### ISSUE TITLE
Is there any way to just get straight tapered outputs in MMI1x2

### ISSUE THREAD

**Issue by peterxsu** [DerekK88/PICwriter#1]
angle=0 for the MMI1x2 seems to get rid of the output tapers entirely instead of just providing the tapered outputs without any sort of s-curves

**Comment by DerekK88** [comment]
Thanks for the report!  Right now, the length of the taper is fixed to be half the length of the S-curve for the two outputs (and for all ports in the 2x2 MMI).  In most cases, an S-curve is recommended to separate the two output port waveguides.

I suppose one way of getting around this would be to add a very slight taper -- pass a separate `WaveguideTemplate` instance to `MMI1x2` that has a very large bending radius, and then make `angle` small.

I think an enhancement would be to add an optional `taper_length` keyword argument to `MMI1x2` so the default value of 1/2 the S-curve can be overwritten.

**Comment by DerekK88** [comment]
Another workaround is to leave `angle=0`, and then just connect a straight [Taper](https://picwriter.readthedocs.io/en/latest/components/couplers.html#picwriter.components.Taper) object to the two outputs.  This will give you complete control over the taper length, start width, end width, etc.
