### ISSUE TITLE
may be the function of MZI is wrong

### ISSUE THREAD

**Issue by ATTICUS2** [DerekK88/PICwriter#10]
https://github.com/DerekK88/PICwriter/blob/8dc6fb550ccd4dd1cf9c04f2362dd26b82a1e8cb/picwriter/components/mzi.py#L173

hi, in the function of   MachZehnder, if i don't want the "heater", i set "heater = False", From my understanding of this function， i think that the attribute "mt" is not need to be defined or set it "None". But ,when i set  "heater = False", no matter how I set "mt",the result is always as the code below. Unless I set "heater = True",and set "mt",  this function will run normally. 
```
 File "/home/ma/anaconda3/envs/mp/lib/python3.6/site-packages/picwriter/components/mzi.py", line 173, in build_cell
    htr_top_in = (x0+self.wgt.bend_radius, y0+self.arm1/2.0+self.wgt.bend_radius+self.mt.width/2.0)
AttributeError: 'MachZehnder' object has no attribute 'mt'
```

**Comment by DerekK88** [comment]
Thank you for this report.  This was indeed a bug, and I had actually never tried implementing them without heaters.  If you reinstall PICwriter manually (not the version currently on PyPI), all of the MZI classes should work correctly.
