### ISSUE TITLE
Y-Splitter component

### ISSUE THREAD

**Issue by gyger** [DerekK88/PICwriter#11]
A Y-splitter component would be I think an interesting addition to the library.

Is this something you want to have?

**Comment by DerekK88** [comment]
Yes, this would be a good addition to the library.  Right now I've defaulted to 1x2 MMI's as power splitters/combiners.  If you have a recommendation on how to parameterize a Y-splitter I'm open to suggestions.

More generally, when I have time I would like to add a tutorial on creating custom components for making PCells.  The structure of the [mmi1x2.py](https://github.com/DerekK88/PICwriter/blob/master/picwriter/components/mmi1x2.py) file would be a good starting point.
