### ISSUE TITLE
Add Superconducting elements

### ISSUE THREAD

**Issue by gyger** [DerekK88/PICwriter#12]
I have implemented superconducting elements (SNSPDs and lumped element inductors) for superconducting layers on top of the photonics. I was wondering if this is something that can be part of the library or if I should make just a picwriter-sc project containing this components.

**Comment by DerekK88** [comment]
Hi gyger,

This is definitely something I would be interested in adding to the library.  If you haven't already, you can go ahead and fork the PICwriter project and try adding a component to the picwriter/components folder.  Perhaps call it snspd.py and inductor.py (something like this).  To add a new component to the library, a couple things need to be done (that I can help with):
- Generate the component file in a manner relatively consistent with the current components (if possible).
- Add these component files to the `picwriter/components` folder
- Update `picwriter/components/__init__.py`
- Add a new nosetest case for each component in `picwriter/tests/test_picwriter.py`
- Add the new element to the documentation in `docs/source/component-documentation.rst` and `docs/source/components/superconducting.rst` (`superconducting.rst` doesn't exist yet, but we can make a new documentation page for these types of elements).

**Comment by gyger** [comment]
Perfect, working on it.

**Comment by chaitalijoshi** [comment]
hi @gyger @DerekK88, wondering if superconducting elements were added to this library?

**Comment by gyger** [comment]
I made some in a local repository but moved to PHIDL for my GDS once they had the path module.
