### ISSUE TITLE
Clearing gdsLibrary is not simple anymore with new duplicate detection

### ISSUE THREAD

**Issue by gyger** [DerekK88/PICwriter#18]
In the past I used the trick to write the following code somewhere in my Jupyter Notebook to initialize a new GDS library.

```
gdspy.current_library = gdspy.GdsLibrary()
cell = circle_grating(width=10)
gdspy.write_gds('tmp_test.gds', unit=1.0e-6, precision=1.0e-9)
```
With the new duplication detection, a cell is not added anymore to the library if it was added before. Somehow Picwriter does not realize that the library has been reset.

**Comment by gyger** [comment]
The solution currently is to also reset the dictionary in the toolkit `tk.CURRENT_CELLS = {}`.

**Comment by gyger** [comment]
One could e.g. provide a function in the toolkit `tk.reset_database()`.

**Comment by DerekK88** [comment]
Thanks for the bugfix.  I've added a reset_database function to the toolkit, as you suggested.  If you think of a better way of resetting these attributes let me know.  I've had the same problem as you and don't know what the most elegant fix is.
