### ISSUE TITLE
Proximity Correction - Integrate variable Doses

### ISSUE THREAD

**Issue by gyger** [DerekK88/PICwriter#2]
Hej,
I was wondering if there is some way how to integrate some manual proximity correction. Unfortunately I do not have access to proximity software, that would fix my GDS, so I have to "manually" integrate it into my mask.

For now I extended the class with an _element_spec_, where I define different elements e.g. focus, teeth.
Perhaps there is a good idea how to solve this?

**Comment by DerekK88** [comment]
Are you referring to [proximity effect correction (PEC)](https://en.wikipedia.org/wiki/Proximity_effect_(electron_beam_lithography)), as is used in electron-beam lithography?

**Comment by gyger** [comment]
Yes, what I do at the moment e.g. for the grating coupler is that I created a member of the class called element_spec. This contains then the items 'focus' and 'teeth' and applies different layers or datatypes (Raith uses the datatype/1000 as dose factor).

This works quite well, for simple structures, but I am unsure how e.g. correct for the doses in the teeth. For larger institutions this is a solved problem due to access to software like Beamer, but unfortunately I do not have access to this tools yet.

**Comment by DerekK88** [comment]
Hm, I am not sure what the solution to this would be using the PICwriter library.  From just my personal experience, the first step is solely generating the GDSII file of the target desired structure.  Then, you convert the GDSII file into the appropriate machine-readable file format (such as .CON/.SCON for Elionix systems, though I am less with Raith & JEOL systems).  During this conversion process, the shot pitch, dose time, write-order, etc. are all specified.  I imagine you could write a script that would perform this conversion process for your tool, incorporating the [proximity effect correction process](http://nanolithography.gatech.edu/proximity.htm).
