### ISSUE TITLE
How to handly copy operations on Templates?

### ISSUE THREAD

**Issue by gyger** [DerekK88/PICwriter#20]
I usually use one Waveguide template and then modify just the datatype (because the Dose in our system is stored in the datatype). For this I use `copy.copy()`. If I now copy the waveguide template, it keeps the same name and afterwards structures that only sweep the Dose (DoseTests) are not regenerated in the GDS, because the duplicate detection thinks it is the same structure (because the Template hase the same name).

It is a edge case, not sure if it is worth fixing (by overriding the __copy__ function of the WaveguideTemplate).

I fix it for now that after copying, I rewrite the name using
```
cur_wgt = copy.copy(wgt)
cur_wgt.name = tk.getCellName("WaveguideTemplate")
```

**Comment by DerekK88** [comment]
Hey gyger,

Sorry for the long delayed response on this!  I like your suggestion of overriding the copy function.  I've gone ahead and implemented this.
