### ISSUE TITLE
Some designs crashing on RAITH Voyager Ebeam

### ISSUE THREAD

**Issue by Miakatt** [DerekK88/PICwriter#25]
I've been using PICWriter for generating simple designs which I write with a Raith Voyager E-beam. All designs are readable with third party software such as KLayout, LayoutEditor, and even the Raith software itself. However, when I try to write some of these designs, the Raith E-beam stops writing at some point. 
I'm the only person to use PICWriter with this machine and the only one to have this problem. Other users make patterns with Matlab_Raith_GDSII or IPKISS software. 
I've brought this issue up with the people at GDSPY and they couldn't find any issues with my example gds file. (https://github.com/heitzmann/gdspy/issues/23#issuecomment-540397802)

My suspicion is that PICWriter is generating quite complicated polynomial shapes for things like grating couplers, whereas other users make these structures with simple <6 sided polygons and rectangles. Then, when it comes to unpacking the gds, Raith has problems with the PICWriter polygons and effectively runs out of memory or gets stuck in a loop.
Has anyone else had issues like this? 

I don't think this is a problem with PICWriter itself; rather, it seems like a problem with how Raith handles the gds file that it generates. I REALLY like PICWriter and I'm loathed to stop using it because of a possible incompatibility with the E-Beam. 

Is it possible to force PICWriter to limit the number of points on any single polynomial shape that it generates?  How would I go about creating a new component class that only uses simple polygons, similar to what the other users generate by hand in Matlab?

**Comment by DerekK88** [comment]
Hey Miakatt, glad to hear you've liked using PICwriter!  Out of curiosity, would you mind re-generating your GDS file, then doing the boolean in KLayout manually (rather than using `build_mask()` in PICwriter)?  `build_mask()` just makes a call to gdspy's fast_boolean functions.  Another option you can try is merge your write-layer prior to processing it in the Raith software.

Finally, if you are concerned about the number of points per polygon, you can open the file in KLayout and when you do "Save As", you can change "Max Vertices" (i.e. the max number of points on the polygons written in the GDS file-- it will auto fracture your shapes so they are all under this number).  This being said, I looked at your GDS and each polygon seems to have <400 points which is totally fine for most GDS readers and ebeam tools.

This could also be a problem with the grating coupler class.  The cladding doesn't extend much beyond the last grating tooth, so perhaps I could extend this in the file.

If you are interested in adding custom cells, I'm working on drafting a PICwriter template and a tutorial for this.  For now though, you can always just use the GDSpy reference and add polygons to your mask, or you can look at some of the files in the /components/ folder of the library.

**Comment by Miakatt** [comment]
I've generated the boolean difference of the core and cladding layers in KLayout. They both look fine, but with minor differences. 
<img width="970" alt="KLayout_Boolean" src="https://user-images.githubusercontent.com/35867921/66703823-8c426f80-ed0e-11e9-8f30-ef955f892860.png">
KLayout Output
<img width="888" alt="PICWriter_Boolean" src="https://user-images.githubusercontent.com/35867921/66703825-8ea4c980-ed0e-11e9-8f09-b20054a61ba2.png">
PICWriter Output

The GDS file can be found at:
https://www.dropbox.com/s/my2g5x3afvycfyc/GC_Sweep_L3-PICWriter_L4_KLayout.gds?dl=0
Layer 3 is the PICWriter generated mask. Layer 4 is the layer differences (Layer2 NOT Layer1) generated in KLayout. 
Please take a look and let me know if you see anything worth investigating further. 

When I get time, I will try writing the KLayout generated mask and see if it still locks up. I'm also hoping that Raith can shed some light on this problem. PICWriter is so easy to use and gives such nice results, it's worth spending some time trying to find a fix for this. 

On the topic of making custom cells, I will soon want to design a star coupler. I'll use the existing components as a guide, but any advise/hints would be very welcome.

**Comment by DerekK88** [comment]
Hi Miakatt,

I think this is an interesting issue, and I don't want to close this just yet, but I'm going to add a Question label to this post.  There is still some work on refining the exact origin of the problem you're experiencing (for example, is it an issue on the mask generation side with picwriter/gdspy, or is it an issue with how the .gds files are being loaded into the Raith tool?).

If you can refine the exact problem you are having down to a minimum working example, or allude to some area of the codebase that isn't working properly, I'd be happy to give it a look and try to fix a bug!

p.s. if you are using an older version of picwriter, it might be worth trying to upgrade it and see if that fixes the problem.  I changed the way smooth polygons are handled last summer (so it correctly determines the # of points in these polygons).

**Comment by Miakatt** [comment]
Hi @DerekK88 , 
Some more news from yesterday. My colleague was using the e-beam yesterday with a pattern made with IPKISS. It was a large pattern, made up of many small polygons. However, the Raith machine locked up. This is the first time we've seen it lock up with anything other than the designs I made using PICWriter. 
So, I think that this is a local issue and not something caused by PICWriter or gdspy. It may be that the way I was making large (15mmx15mm) patterns in PICWriter (because it's soooo easy to do so! :) ), the machine was locking up more frequently. Now we have an equivalent example generated purely in IPKISS. 
I think it is okay to close this thread. 

I shall make sure I have the latest build installed and get back to using PICWriter, limiting the pattern size until Raith fix the issue. 

Thank you for your assistance.

**Comment by gyger** [comment]
Hej Miakatt, I think it it as common problem with the Voyager Raith System, that it is not reliably exposing patterns.

**Comment by Miakatt** [comment]
Hi Gyger.
We found that limiting our maximum number of polygon vertices to 200 cured the intermittent crashing. Raith also found a thread memory management issue in their software.
However, we still see errors in fine detailed elements such as grating couplers. Some will be written correctly, while others will have bits missing. This happens even when the components are on the same gds file and the same chip.

Safe to say, picwriter was not at fault here.
