### ISSUE TITLE
How to get length of waveguide

### ISSUE THREAD

**Issue by AlanJamesBell** [DerekK88/PICwriter#29]
I think this is a common request in photonics designs where keeping phase as coherent as possible is required. I've searched the documentation for toolkit and gdspy, but I'm unable to find a reasonably simple way to return the path length of a waveguide.
Any suggestions if this could be done in PICWriter?

**Comment by DerekK88** [comment]
Hi  @AlanJamesBell,

First, sorry this reply comes months after your inquiry.  Thanks for checking out the repo and for posting this question.

There exists an older method for getting the length of a waveguide with circular or Euler bends, `tk.get_trace_length(trace, wgt)`.  `wgt` is a WaveguideTemplate object, and `trace` is a list of (x,y) points all specifying 90 degree angles.  The need to calculate exact waveguide lengths for non-manhattan traces is (I think) quite important, so I’ve added a `length` attribute to all waveguide objects (ea2d0f2). This attribute will compute the length for _any_ trace, even non-Manhattan ones, so I'd recommend using this.  The length information is currently only computed for strip and slot waveguides-- I haven’t yet added this for sub wavelength grating waveguides.  Once you create a waveguide (`my_waveguide = Waveguide(...)`), this value (in units of microns) can now be accessed directly: `my_wg.length`.

As always, trust but please verify too.  And let us know if you find anything that needs fixing.
