### ISSUE TITLE
SWG routing issue

### ISSUE THREAD

**Issue by DerekK88** [DerekK88/PICwriter#4]
@peterxsu : Issue with block generation in SWG waveguides.  See example code below for the error:

```
top = gdspy.Cell("top")
wgt= WaveguideTemplate(wg_type='swg', wg_width=1.0, bend_radius=25, duty_cycle=0.50, period=1.0, resist='+', fab="ETCH")
wg=Waveguide([(0, 20.0), (90.0, 20.0), (90.0, 70.0), (200, 70.0)], wgt)
tk.add(top, wg)
gdspy.LayoutViewer()
```
Seems like a rounding error when determining the number of blocks.
![swg_error](https://user-images.githubusercontent.com/3423351/50740449-97cf9b80-11bc-11e9-8eeb-b8cc93b86f88.png)

**Comment by peterxsu** [comment]
I think I fixed it. It was an issue with the remaining period between consecutive sections. See new pull request
