### ISSUE TITLE
The documentation is not updated, causing some examples to not work properly

### ISSUE THREAD

**Issue by ATTICUS2** [DerekK88/PICwriter#8]
hello!
https://github.com/DerekK88/PICwriter/blob/a98799316852cf773608df5f548bd04695f49510/docs/source/tutorial.rst#L183-L184
0eac4d27546fd263208cb6e39252bbb09cc3e584
The tutorial code in the above documentation does not work properly, as if it was caused by this commit 0eac4d2.
```
Error details：
ValueError: Warning!  Given the WaveguideTemplate 'bend radius' and 'spacing' specified, no spiral can be fit within the requested 'width'.  Please increase the 'width'.

```

**Comment by DerekK88** [comment]
Hello!  Thanks for pointing my attention to this.  The documentation was, in fact, in need of updating.  The issue with the Spiral waveguides was a result of some changes to the Spiral class implementation, so the documentation version was not accurate.

I've just pushed some changes to the documentation to correct this now, with proper Spiral instantiation as detailed [here](https://picwriter.readthedocs.io/en/latest/components/spirals.html).
